#!/usr/bin/env bash

rm -rf ghc.nix
git clone --depth=1 --branch=master https://github.com/alpmestan/ghc.nix.git ghc.nix
rm -rf ./ghc.nix/.git
sources=./ghc.nix/nix/sources.json
nixpkgs_rev="$(jq -r '.nixpkgs.rev' $sources)"
nixpkgs_unstable_rev="$(jq -r '."nixpkgs-unstable".rev' $sources)"
tmp="$(mktemp)"
cp flake-template.nix "$tmp"
sed -i "s/NIXPKGS_REV/$nixpkgs_rev/g" "$tmp"
sed -i "s/NIXPKGS_UNSTABLE_REV/$nixpkgs_unstable_rev/g" "$tmp"
mv "$tmp" flake.nix
nix flake update
