#!/usr/bin/env bash

sources=./ghc.nix/nix/sources.json
nixpkgs_rev="$(jq -r '.nixpkgs.rev' $sources)"
nixpkgs_unstable_rev="$(jq -r '."nixpkgs-unstable".rev' $sources)"
tmp="$(mktemp)"
cp flake-template.nix "$tmp"
sed -i "s/NIXPKGS_REV/$nixpkgs_rev/g" "$tmp"
sed -i "s/NIXPKGS_UNSTABLE_REV/$nixpkgs_unstable_rev/g" "$tmp"
mv "$tmp" flake.nix
nix flake update
